export interface ProductSpecification {
  size: string
  speed: number
  od: number
  td: number
  sw: string
  rim: string
  load: number
  pressure: number
  loadIndex: string
}

export interface Product {
  id: string
  name: string
  category: string
  position: string
  application: string
  image: string
  description: string
  fullDescription?: string
  features: string[]
  sizes: string[]
  specifications?: ProductSpecification[]
  benefits?: string[]
  applications?: string[]
  compound?: string
  compound_description?: string
}

export const products: Product[] = [
  // OTR Products
  {
    id: "rem1",
    name: "REM-1",
    category: "otr",
    position: "E-3/L-3",
    application: "Earthmover/Loader",
    image: "/images/tire-otr.jpg",
    description: "Desain tapak multi-fungsi non-directional untuk aplikasi pertambangan dan konstruksi. OEM Certified dengan retreadability superior.",
    fullDescription: "REM-1 adalah ban OTR generasi terdahulu yang dirancang khusus untuk earthmover dan loader dengan desain tapak multi-fungsi non-directional. Dioptimalkan untuk aplikasi pertambangan dan konstruksi, REM-1 menawarkan traksi superior di berbagai medan dengan compound yang seimbang.",
    features: ["Multi-fungsi non-directional", "OEM Certified", "Retreadable"],
    sizes: ["17.5R25", "20.5R25", "23.5R25", "26.5R25", "29.5R25"],
    benefits: ["OEM Certified untuk berbagai manufaktur", "Desain retreadable untuk ekonomi operasional", "Compound multi-fungsi untuk versatilitas"],
    applications: ["Earthmover", "Wheel Loader", "Excavator"],
    compound: "Natural Rubber Blend",
  },
  {
    id: "rem2",
    name: "REM-2 / REM-2N",
    category: "otr",
    position: "E-3/L-3",
    application: "Earthmover/Loader",
    image: "/images/tire-otr.jpg",
    description: "Desain tapak multi-fungsi non-directional untuk penggunaan optimal pada peralatan. Traksi superior di pasir, batu, lumpur dan permukaan lainnya. OEM Certified.",
    fullDescription: "REM-2 dan REM-2N adalah ban OTR untuk earthmover dan loader dengan desain tapak multi-fungsi non-directional yang optimal. Varian REM-2N merupakan improved version dengan compound yang lebih tahan terhadap cut dan chip. Traksi superior di pasir, batu, dan lumpur.",
    features: ["Multi-fungsi non-directional", "OEM Certified", "Retreadable", "Varian REM-2N improved"],
    sizes: ["17.5R25", "20.5R25", "23.5R25", "26.5R25", "29.5R25"],
    benefits: ["Traksi optimal di berbagai medan", "Umur tapak yang panjang", "OEM certification untuk kendaraan berat"],
    applications: ["Earthmover", "Wheel Loader", "Dump Truck"],
    compound: "Premium Natural Rubber",
  },
  {
    id: "rem3",
    name: "REM-3",
    category: "otr",
    position: "E-3/L-3",
    application: "Earthmover/Loader",
    image: "/images/tire-otr.jpg",
    description: "Desain uni-directional untuk traksi maksimum dan stabilitas. Peningkatan umur tapak dengan compound optimal di aplikasi berat.",
    fullDescription: "REM-3 merupakan evolusi dari REM series dengan desain uni-directional yang memberikan traksi maksimum dan stabilitas superior. Compound khusus dirancang untuk menahan keausan di aplikasi earthmover dan loader berat, dengan umur tapak yang signifikan lebih panjang.",
    features: ["Uni-directional design", "Radial design", "Maximum traction", "Enhanced durability"],
    sizes: ["17.5R25", "20.5R25", "23.5R25"],
    benefits: ["Traksi maksimum di kondisi berat", "Stabilitas yang lebih baik", "Umur tapak extended"],
    applications: ["Earthmover", "Loader", "Mobile Equipment"],
    compound: "Advanced Mining Compound",
  },
  {
    id: "rem4",
    name: "REM-4",
    category: "otr",
    position: "E-4",
    application: "Earthmover Heavy Duty",
    image: "/images/tire-otr.jpg",
    description: "Desain tapak baru memperkuat cengkeraman ban dan meningkatkan traksi di aplikasi pertambangan berat. Formula tapak unik memberikan ketahanan aus superior.",
    fullDescription: "REM-4 adalah ban OTR untuk aplikasi earthmover heavy duty dengan desain tapak baru yang memperkuat cengkeraman. Formula compound unik memberikan ketahanan aus yang superior dan resistance terhadap cut dan chip yang excellent di lingkungan pertambangan ekstrem.",
    features: ["Heavy duty design", "Excellent wear resistance", "Mining compound", "Superior grip"],
    sizes: ["26.5R25", "29.5R25"],
    benefits: ["Traksi superior di hard rock mining", "Ketahanan aus yang exceptional", "Cost per hour yang rendah"],
    applications: ["Earthmover", "Articulated Truck", "Heavy Equipment"],
    compound: "Heavy Duty Mining Blend",
  },
  {
    id: "rem6",
    name: "REM-6",
    category: "otr",
    position: "IND-4",
    application: "Industrial/Port/Forklift",
    image: "/images/tire-otr.jpg",
    description: "Desain tapak rata dan lebar memberikan performa traksi optimal. Compound khusus melawan keausan cepat dan tusukan di aplikasi industrial.",
    fullDescription: "REM-6 adalah ban OTR dengan desain tapak rata dan lebar untuk aplikasi industrial, port, dan forklift. Tapak lebar memberikan footprint yang stabil dan distribusi beban merata. Compound khusus dirancang untuk resistance terhadap keausan cepat, tusukan, dan sidewall flexing.",
    features: ["Flat wide tread", "Anti-puncture compound", "Stabilitas tinggi", "Wide size range"],
    sizes: ["6.50R10", "7.00R12", "7.00R15", "8.25R15", "12.00R20"],
    benefits: ["Stabilitas lateral maksimal", "Anti-puncture protection", "Cocok untuk berbagai aplikasi", "Long service life"],
    applications: ["Port Equipment", "Forklift", "Material Handling", "Ground Support"],
    compound: "Industrial Grade Compound",
  },
  {
    id: "rem7",
    name: "REM-7",
    category: "otr",
    position: "E-4",
    application: "Dump Truck Haulage",
    image: "/images/tire-otr.jpg",
    description: "Compound khusus untuk menahan aplikasi pertambangan berat. Desain radial memperpanjang umur ban dengan deep tread depth optimal.",
    fullDescription: "REM-7 adalah ban OTR untuk dump truck dan haulage di aplikasi pertambangan dengan deep tread depth. Compound mining khusus dirancang untuk tahan terhadap heat buildup, cut, dan chip. Desain radial memperpanjang umur ban dengan menjaga distribusi beban yang optimal.",
    features: ["Mining compound", "Deep tread depth", "Non-directional center rib", "Extended service life"],
    sizes: ["18.00R33", "21.00R33", "24.00R35"],
    benefits: ["Umur tapak extended", "Heat resistance tinggi", "Traksi di berbagai medan", "Cut resistance superior"],
    applications: ["Dump Truck", "Haulage Truck", "Articulated Truck"],
    compound: "Deep Tread Mining Compound",
  },
  {
    id: "rem8",
    name: "REM-8",
    category: "otr",
    position: "E-2",
    application: "Mobile Crane",
    image: "/images/tire-otr.jpg",
    description: "Ban mobile crane kecepatan tinggi untuk aplikasi jalan raya dan off-road. Pola tapak universal memberikan traksi meningkat. DOT approved dan OEM Certified.",
    fullDescription: "REM-8 adalah ban OTR khusus mobile crane dengan kemampuan kecepatan tinggi untuk aplikasi mixed use (jalan raya dan off-road). Pola tapak universal memberikan grip optimal baik di aspal maupun medan off-road. DOT approved dan OEM Certified oleh major crane manufacturers.",
    features: ["DOT approved", "OEM Certified", "Highway & off-road", "Universal tread pattern"],
    sizes: ["14.00R24", "14.00R25", "16.00R25", "20.5R25"],
    benefits: ["Dual use (jalan raya dan off-road)", "Speed rating tinggi", "OEM certified", "Traksi universal"],
    applications: ["Mobile Crane", "High Speed Transport", "Multi-terrain"],
    compound: "Highway-Off-road Blend",
  },
  {
    id: "rem82",
    name: "REM-82",
    category: "otr",
    position: "E-2",
    application: "Mobile Crane Premium",
    image: "/images/tire-otr.jpg",
    description: "Ban mobile crane premium dengan compound khusus untuk stabilitas maksimal di aplikasi jalan raya dan off-road. Enhanced durability dan cut resistance.",
    fullDescription: "REM-82 adalah premium variant dari REM-8 untuk mobile crane dengan compound enhanced untuk stabilitas dan durability maksimal. Dirancang untuk aplikasi demanding dengan mixed highway dan off-road usage. Cut resistance dan thermal stability yang superior dibanding generasi sebelumnya.",
    features: ["Premium compound", "Enhanced durability", "Cut resistant", "Thermal stable"],
    sizes: ["14.00R24", "14.00R25"],
    benefits: ["Durability yang superior", "Stabilitas maksimal di kurva", "Thermal management lebih baik", "Extended mileage"],
    applications: ["Premium Mobile Crane", "High Performance Equipment"],
    compound: "Premium Thermal Compound",
  },
  {
    id: "rem9",
    name: "REM-9",
    category: "otr",
    position: "E-4",
    application: "Dump Truck Mining",
    image: "/images/tire-otr.jpg",
    description: "Compound khusus untuk menahan aplikasi pertambangan berat dengan deep tread depth. Desain radial OTR memperpanjang umur ban dan mendukung retreadability.",
    fullDescription: "REM-9 adalah ban OTR dump truck untuk aplikasi pertambangan berat dengan deep initial tread depth dan mining-specific compound. Dirancang untuk extreme conditions dengan excellent cut resistance dan heat buildup control. Retreadable untuk economic operation.",
    features: ["Mining compound", "Deep tread depth", "Extended service life", "Retreadable"],
    sizes: ["26.5R25", "29.5R25", "18.00R33", "21.00R33"],
    benefits: ["Umur tapak panjang", "Mining durability", "Cost per hour rendah", "Retreadable option"],
    applications: ["Dump Truck Mining", "Haulage", "Articulated Truck"],
    compound: "Extreme Mining Compound",
  },
  {
    id: "rem10",
    name: "REM-10 / REM-10PRO",
    category: "otr",
    position: "E-3",
    application: "Dump Truck",
    image: "/images/tire-otr.jpg",
    description: "Desain tapak multi-fungsi non-directional untuk penggunaan optimal pada dump truck. Performa OTR superior di berbagai jenis medan dengan OEM Certification.",
    fullDescription: "REM-10 adalah ban OTR untuk dump truck dengan desain tapak multi-fungsi non-directional. REM-10PRO adalah improved version dengan compound enhanced untuk durability yang lebih baik. Optimal untuk berbagai jenis medan dari hard rock hingga soft terrain.",
    features: ["Center block tread", "Even wear", "OEM Certified", "Multi-terrain capable"],
    sizes: ["14.00R25", "16.00R25", "26.5R25", "29.5R25"],
    benefits: ["Multi-fungsi untuk berbagai medan", "Umur tapak merata", "OEM certification", "Versatile performance"],
    applications: ["Dump Truck", "Construction Vehicle", "Articulated Truck"],
    compound: "Balanced Multi-terrain Compound",
  },
  {
    id: "rem12",
    name: "REM-12",
    category: "otr",
    position: "L-5",
    application: "Loader",
    image: "/images/tire-otr.jpg",
    description: "Desain tapak multi-fungsi non-directional dengan traksi superior di pasir, batu, lumpur. Desain blok tengah unik memberikan traksi tambahan dan keausan merata.",
    fullDescription: "REM-12 adalah ban OTR untuk wheel loader dengan desain tapak multi-fungsi non-directional. Center block design yang unik memberikan traksi tambahan dengan keausan yang merata. Optimal untuk aplikasi loader di pasir, batu, dan lumpur.",
    features: ["Multi-function design", "Center block tread", "Even wear", "Superior grip"],
    sizes: ["17.5R25", "26.5R25", "29.5R25"],
    benefits: ["Traksi superior", "Keausan merata", "Stabilitas loader", "Umur tapak panjang"],
    applications: ["Wheel Loader", "Loader Application"],
    compound: "Loader Optimized Compound",
  },
  {
    id: "rem18",
    name: "REM-18",
    category: "otr",
    position: "L-5",
    application: "Loader",
    image: "/images/tire-otr.jpg",
    description: "Tapak lebar untuk stabilitas maksimal. Desain tapak directional untuk traksi off-road yang meningkat. Compound anti-cut dan chip memperpanjang umur ban.",
    fullDescription: "REM-18 adalah ban OTR untuk loader dengan wide tread footprint untuk stabilitas lateral maksimal. Directional tread pattern memberikan traksi off-road yang superior. Anti-cut dan anti-chip compound memperpanjang umur ban signifikan di aplikasi keras.",
    features: ["Wide footprint", "Directional tread", "Anti-cut compound", "Retreadable"],
    sizes: ["35/65R33"],
    benefits: ["Stabilitas maksimal", "Traksi off-road excellent", "Cut resistance", "Long service life"],
    applications: ["Large Wheel Loader", "Articulated Loader"],
    compound: "Large Loader Compound",
  },
  {
    id: "rem19",
    name: "REM-19",
    category: "otr",
    position: "L-5",
    application: "Loader",
    image: "/images/tire-otr.jpg",
    description: "Pola tapak non-directional dengan rib tengah memberikan traksi yang ditingkatkan. Tapak lebar untuk stabilitas dan compound anti-cut chip.",
    fullDescription: "REM-19 adalah ban OTR untuk loader dengan non-directional pattern dan center rib design. Center rib memberikan traksi tambahan sambil mempertahankan fleksibilitas tapak. Wide tread untuk stabilitas dengan anti-cut dan anti-chip compound.",
    features: ["Center rib design", "Wide tread", "Stability focus", "Retreadable"],
    sizes: ["20.5R25", "23.5R25", "26.5R25", "29.5R25"],
    benefits: ["Stabilitas lateral excellent", "Traksi center rib", "Anti-cut protection", "Extended tire life"],
    applications: ["Wheel Loader", "Loader Application"],
    compound: "Loader Performance Compound",
  },
  {
    id: "rem21",
    name: "REM-21+",
    category: "otr",
    position: "L-3",
    application: "Loader Performance",
    image: "/images/tire-otr.jpg",
    description: "Generasi terbaru loader tire dengan compound enhanced dan tread design yang optimal. Performa traksi superior dengan umur ban yang lebih panjang.",
    fullDescription: "REM-21+ adalah generasi terbaru dari REM series untuk loader dengan compound enhanced dan advanced tread design. Dirancang untuk performa optimal dengan traksi superior dan umur ban yang signifikan lebih panjang. Teknologi terbaru Double Coin untuk loader application.",
    features: ["Enhanced compound", "Advanced tread design", "Improved traction", "Extended lifespan"],
    sizes: ["17.5R25", "20.5R25", "23.5R25"],
    benefits: ["Traksi superior", "Umur ban extended", "Performa optimal", "Modern technology"],
    applications: ["Wheel Loader", "High Performance Loader"],
    compound: "Advanced Loader Compound",
  },
  {
    id: "rem29",
    name: "REM-29",
    category: "otr",
    position: "E-4/L-4",
    application: "Articulated Dump Truck",
    image: "/images/tire-otr.jpg",
    description: "Ban untuk dump truck artikulasi dengan desain multi-fungsi. Traksi superior dan stabilitas di medan berat dengan compound mining.",
    fullDescription: "REM-29 adalah ban OTR khusus untuk articulated dump truck dengan desain multi-fungsi untuk dual positioning. Compound mining khusus memberikan traksi superior dan stabilitas di medan berat. Optimal untuk aplikasi mining dengan articulated configuration.",
    features: ["Multi-functional design", "Mining compound", "Dual positioning capable", "Heavy duty"],
    sizes: ["23.5R25", "26.5R25", "29.5R25"],
    benefits: ["Fleksibilitas posisi roda", "Traksi mining", "Stabilitas articulasi", "Durability tinggi"],
    applications: ["Articulated Dump Truck", "Mining Transport"],
    compound: "Articulated Truck Compound",
  },
  {
    id: "rem17",
    name: "REM-17",
    category: "industrial",
    position: "IND-4",
    application: "Port Equipment",
    image: "/images/tire-industrial.jpg",
    description: "Tapak rata dan lebar memberikan performa dan keausan optimal. Stabilitas luar biasa dengan gerakan lateral berkurang untuk aplikasi pelabuhan.",
    fullDescription: "REM-17 adalah ban OTR untuk port equipment dengan flat dan wide tread design. Performa optimal di kondisi pelabuhan dengan reduced lateral movement. Stabilitas luar biasa dengan durability yang superior untuk 24/7 port operations.",
    features: ["Flat wide tread", "Port specific design", "Lateral stability", "High durability"],
    sizes: ["16.00R25"],
    benefits: ["Stabilitas port", "Durability exceptional", "Predictable handling", "Long life"],
    applications: ["Port Equipment", "Industrial Terminal"],
    compound: "Port Application Compound",
  },
  {
    id: "rem26",
    name: "REM-26",
    category: "industrial",
    position: "IND-4",
    application: "Ground Support Equipment",
    image: "/images/tire-industrial.jpg",
    description: "Desain tapak rata, lebar dan terbuka memberikan performa traksi optimal. Compound khusus melawan keausan cepat dan tusukan di aplikasi GSE.",
    fullDescription: "REM-26 adalah ban OTR untuk ground support equipment dengan open tread design. Tapak rata dan lebar memberikan optimal footprint untuk traksi dan stabilitas. Compound anti-puncture dan anti-wear untuk GSE applications.",
    features: ["Open tread design", "Anti-puncture compound", "Wide size range", "GSE optimized"],
    sizes: ["6.50R10", "7.00R15", "12.00R20"],
    benefits: ["Anti-puncture protection", "GSE durability", "Wide range support", "Maintenance friendly"],
    applications: ["GSE", "Tug", "Tow Tug", "Industrial Equipment"],
    compound: "GSE Specific Compound",
  },
  {
    id: "dt301",
    name: "DT-301 / DT-301 PRO",
    category: "otr",
    position: "E-3",
    application: "Dump Truck",
    image: "/images/tire-otr.jpg",
    description: "Desain pola dengan saturasi tinggi dan design anti-tusuk untuk durabilitas maksimal. Kawat baja struktural berkekuatan tinggi untuk load carrying capacity superior.",
    fullDescription: "DT-301 dan DT-301 PRO adalah ban OTR dump truck dengan high saturation tread pattern. Design anti-puncture untuk durabilitas maksimal di aplikasi berat. Kawat baja berkekuatan tinggi memberikan load carrying capacity superior dan structural integrity.",
    features: ["High saturation design", "Anti-puncture", "Heavy load capacity", "Structural integrity"],
    sizes: ["14.00R25", "16.00R25"],
    benefits: ["Durability maksimal", "Anti-puncture protection", "Load carrying superior", "Structural strength"],
    applications: ["Dump Truck", "Heavy Truck"],
    compound: "Heavy Truck Compound",
  },
  {
    id: "dt302",
    name: "DT-302 / DT-302 MAX",
    category: "otr",
    position: "E-3",
    application: "Dump Truck Standard",
    image: "/images/tire-otr.jpg",
    description: "Desain pola besar dengan saturasi pola lebih tinggi dan design anti-tusuk untuk bagian bawah alur. Kawat baja struktural baru berkekuatan tinggi.",
    fullDescription: "DT-302 dan DT-302 MAX adalah ban dump truck standard dengan pola besar dan saturasi tinggi. Design anti-puncture khusus di bagian bawah alur untuk durability. Kawat baja struktural berkekuatan tinggi untuk load capacity maksimal.",
    features: ["Large pattern blocks", "High saturation", "Anti-puncture design", "Structural reinforcement"],
    sizes: ["14.00R25", "16.00R25"],
    benefits: ["Durability enhanced", "Puncture resistance", "Load capacity", "Reliability tinggi"],
    applications: ["Dump Truck", "Construction Truck"],
    compound: "Standard Dump Truck Compound",
  },
  {
    id: "dt303",
    name: "DT-303",
    category: "otr",
    position: "E-4",
    application: "Dump Truck Heavy",
    image: "/images/tire-otr.jpg",
    description: "Ban dump truck untuk aplikasi berat dengan pola blok besar. Anti-tusuk design dan compound khusus dengan heat buildup rendah.",
    fullDescription: "DT-303 adalah ban dump truck untuk heavy duty applications dengan large block pattern. Anti-puncture design dan heat-resistant compound untuk aplikasi ekstrem. Thermal management superior dengan heat buildup control yang excellent.",
    features: ["Large block pattern", "Heavy duty", "Stone ejection ribs", "Heat resistant"],
    sizes: ["14.00R25", "16.00R25"],
    benefits: ["Heavy duty performance", "Stone ejection", "Heat resistance", "Extended life"],
    applications: ["Dump Truck Heavy", "Mining Truck"],
    compound: "Heavy Duty Heat Resistant",
  },
  {
    id: "dt401",
    name: "DT-401",
    category: "otr",
    position: "E-4",
    application: "Dump Truck Mining",
    image: "/images/tire-otr.jpg",
    description: "Blok tapak lebih besar, kedalaman alur lebih dalam, dengan rib pembuangan batu anti-tusuk. Compound mining khusus dengan heat buildup rendah dan cut resistance tinggi.",
    fullDescription: "DT-401 adalah ban dump truck mining premium dengan large block pattern dan deep tread depth. Stone ejection ribs untuk anti-puncture protection. Compound mining khusus dengan excellent cut resistance dan thermal stability untuk extreme mining conditions.",
    features: ["Mining compound", "Stone ejection ribs", "Deep tread depth", "Cut resistant"],
    sizes: ["14.00R25", "16.00R25"],
    benefits: ["Mining durability", "Cut resistance", "Stone protection", "Extended service"],
    applications: ["Dump Truck Mining", "Mining Operations"],
    compound: "Premium Mining Compound",
  },
  {
    id: "rem41",
    name: "REM-41",
    category: "otr",
    position: "E-3/L-3",
    application: "Articulated Dump Truck",
    image: "/images/tire-otr.jpg",
    description: "Ban untuk articulated dump truck dengan design multi-fungsi. Traksi optimal di berbagai medan dengan compound yang seimbang untuk earthmover dan loader.",
    fullDescription: "REM-41 adalah ban OTR untuk articulated dump truck dengan multi-functional design. Compound yang seimbang memberikan performa optimal baik untuk posisi earthmover maupun loader. Traksi superior di berbagai medan dari hard rock hingga soft terrain.",
    features: ["Dual position capable", "Multi-functional", "Balanced compound", "Versatile design"],
    sizes: ["20.5R25", "23.5R25", "26.5R25"],
    benefits: ["Flexibilitas posisi", "Traksi universal", "Durability balance", "Cost effective"],
    applications: ["Articulated Truck", "Dump Truck"],
    compound: "Balanced Articulated Compound",
  },
  {
    id: "rem42",
    name: "REM-42",
    category: "otr",
    position: "L-4",
    application: "Wheel Loader Premium",
    image: "/images/tire-otr.jpg",
    description: "Ban wheel loader generasi terbaru dengan compound premium dan design tread yang advanced. Performa superior dengan umur ban extended.",
    fullDescription: "REM-42 adalah ban wheel loader generasi terbaru dengan premium compound dan advanced tread design. Dirancang untuk performa superior dengan traksi maksimal dan umur ban yang significantly extended. Teknologi Double Coin terbaru untuk optimal loader performance.",
    features: ["Premium compound", "Advanced tread design", "Extended service life", "Superior performance"],
    sizes: ["17.5R25", "20.5R25", "23.5R25"],
    benefits: ["Traksi premium", "Umur ban extended", "Performa superior", "ROI optimized"],
    applications: ["Wheel Loader Premium", "High Performance Loader"],
    compound: "Premium Advanced Compound",
  },
]
